# Generated by Django 5.2.7 on 2025-10-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
