# Generated by Django 5.2.8 on 2025-11-13 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0002_alter_bus_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bus.seats')),
                ('shidule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shidule', to='bus.shidule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
