# Generated by Django 5.2.6 on 2025-10-02 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Bus_seates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A1', models.BooleanField()),
                ('A2', models.BooleanField()),
                ('B1', models.BooleanField()),
                ('B2', models.BooleanField()),
                ('C1', models.BooleanField()),
                ('C2', models.BooleanField()),
                ('D1', models.BooleanField()),
                ('D2', models.BooleanField()),
                ('E1', models.BooleanField()),
                ('E2', models.BooleanField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_apis.bus_list')),
            ],
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('am', models.BooleanField()),
                ('pm', models.BooleanField()),
                ('status', models.CharField(choices=[('TRIP', 'On a trip'), ('NO', 'Not on a trip')], max_length=10)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_apis.bus_list')),
            ],
        ),
    ]
