# Generated by Django 5.2.6 on 2025-10-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_list',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
