# Generated by Django 5.2.7 on 2025-11-03 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A1', models.BooleanField(default=False)),
                ('A2', models.BooleanField(default=False)),
                ('B1', models.BooleanField(default=False)),
                ('B2', models.BooleanField(default=False)),
                ('C1', models.BooleanField(default=False)),
                ('C2', models.BooleanField(default=False)),
                ('D1', models.BooleanField(default=False)),
                ('D2', models.BooleanField(default=False)),
                ('E1', models.BooleanField(default=False)),
                ('E2', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='seats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='buses.seats'),
        ),
    ]
