# Generated by Django 5.2.7 on 2025-11-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_seats_bus_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shidule',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
