# Generated by Django 5.2.7 on 2025-11-03 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_alter_shidule_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='seats',
        ),
        migrations.AddField(
            model_name='seats',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='buses.bus'),
        ),
        migrations.AddField(
            model_name='seats',
            name='toal_seats',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
