# Generated by Django 5.2.7 on 2025-11-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_remove_bus_seats_seats_bus_seats_toal_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seats',
            old_name='toal_seats',
            new_name='total_seats',
        ),
    ]
