# Generated by Django 5.2.8 on 2025-11-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='type',
            field=models.CharField(choices=[('AC', 'ac'), ('NON_AC', 'non_ac')], default='NON_AC', max_length=10),
        ),
    ]
