# Generated by Django 5.2.8 on 2025-11-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_alter_bus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shidule',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
