# Generated by Django 5.2.8 on 2025-12-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_shidule_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shidule',
            name='bus_time',
        ),
        migrations.AddField(
            model_name='shidule',
            name='bus_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
